---
- name: Check for existence of ZSH.
  command: "which zsh"
  register: zsh_exists
  failed_when: "'{{ zsh_path }}' not in zsh_exists.stdout"
  always_run: true

- name: Ensure /etc/shells contians ZSH.
  lineinfile:
    dest: "/etc/shells"
    line: "{{ zsh_path }}"
  always_run: true
  become: true

- name: Find all current users.
  command: "users"
  register: users
  always_run: true

- name: Set ZSH shell as default if specified.
  command: "sudo chsh -s {{ zsh_path }} {{ item }}"
  with_items: "{{ zsh_default_shell_users }}"
  when: "'{{ item }}' in '{{ users.stdout }}'"
  become: true
  always_run: true

- name: Check if Oh My ZSH is installed.
  stat:
    path: "{{ oh_my_zsh_install_directory }}"
  register: oh_my_zsh_installed
  always_run: true

- name: Create temp directory for Oh My ZSH installer.
  command: "mktemp -d"
  register: oh_my_zsh_temp_dir
  when: "not {{ oh_my_zsh_installed.stat.exists|bool }}"

- name: Download Oh My ZSH installer.
  get_url:
    url: "{{ oh_my_zsh_installer_url }}"
    dest: "{{ oh_my_zsh_temp_dir.stdout }}/install.sh"
  when: "not {{ oh_my_zsh_installed.stat.exists|bool }}"

- name: Run Oh My ZSH installer.
  command: "sudo -u {{ item }} sh {{ oh_my_zsh_temp_dir.stdout }}/install.sh"
  with_items: "{{ zsh_default_shell_users }}"
  when: "not {{ oh_my_zsh_installed.stat.exists|bool }} and '{{ item }}' in '{{ users }}'"
  become: true
  register: oh_my_zsh_installer_output
  # failed_when:

- debug: var=oh_my_zsh_installer_output
