---
- name: Check for existence of zsh.
  command: "which zsh"
  register: zsh_exists
  failed_when: "'{{ zsh_path }}' not in zsh_exists.stdout"
  always_run: true

- name: Ensure /etc/shells contians zsh.
  lineinfile:
    dest: "/etc/shells"
    line: "{{ zsh_path }}"
  always_run: true
  become: true

- name: Find all current users.
  command: "users"
  register: users
  always_run: true

- name: Set zsh shell as default if specified.
  command: "sudo -u {{ item }} chsh -s {{ zsh_path }}"
  with_items: "{{ zsh_default_shell_users }}"
  when: "{{ item }} in {{ users.stdout }}"
  become: true
  always_run: true

- name: Create temp directory for OMZ install.
  command: "mktemp -d"
  register: oh_my_zsh_temp_dir
  # when:

- name: Download Oh My ZSH installer.
  get_url:
    url: "{{ zsh_installer_url }}"
    dest: "{{ oh_my_zsh_temp_dir.stdout }}/install.sh"
  # when:

- name: Run Oh My ZSH installer.
  command: "sh {{ oh_my_zsh_temp_dir.stdout }}/install.sh"
  # failed_when:


