---
# Does zsh even exist?
- name: Check for existence of zsh.
  command: "which xsh"
  register: zsh_exists
  always_run: true

- fail: msg="The zsh binary cannot be found!"
  when: "'{{ fish_path }}' not in fish_exists.stdout"

# Make sure /bin/zsh is contained in /etc/shells
- name: Check if /etc/shells already contians zsh.
  command: "grep -x {{ zsh_path }} /etc/shells"
  register: zsh_in_shells
  always_run: true

# Set zsh to default shell if appropriate

# Install oh-my-zsh

- name: Debug `zsh_exists` variable
  debug:
    var: zsh_exists

- name: Debug `zsh_in_shells` variable
  debug:
    var: zsh_in_shells
