---
# Does zsh even exist?
- name: Check for existence of zsh.
  command: "which zsh"
  register: zsh_exists
  failed_when: "'{{ zsh_path }}' not in zsh_exists.stdout"
  always_run: true

# Make sure /bin/zsh is contained in /etc/shells
- name: Check if /etc/shells already contians zsh.
  lineinfile:
    dest: "/etc/shells"
    line: "{{ zsh_path }}"
  always_run: true
  become: true

# Set zsh to default shell if appropriate

# Install oh-my-zsh

- name: Debug `zsh_exists` variable
  debug:
    var: zsh_exists

- name: Debug `zsh_in_shells` variable
  debug:
    var: zsh_in_shells
