---
- name: Check for existence of zsh.
  command: "which zsh"
  register: zsh_exists
  failed_when: "'{{ zsh_path }}' not in zsh_exists.stdout"
  always_run: true

- name: Check if /etc/shells already contians zsh.
  lineinfile:
    dest: "/etc/shells"
    line: "{{ zsh_path }}"
  always_run: true
  become: true

- name: change shell from bash to zsh
  user:
    name: "{{ user.name }}"
    shell: "{{ zsh_path }}"
  when: "{{ make_zsh_default_shell|bool }}"
  always_run: true

# Install oh-my-zsh
