---
# Make sure zsh is installed and minimally configured.
- include: zsh.yml
  tags:
    - zsh
    - configure
    - configure-zsh

# Install oh-my-zsh.
- include: oh-my-zsh-install.yml
  tags:
    - oh-my-zsh
    - install
    - install-oh-my-zsh

# Configure oh-my-zsh with a custom .zshrc template if oh_my_zsh_zshrc_create
# is set to 'true'.
- include: oh-my-zsh-zshrc.yml
  tags:
    - oh-my-zsh
    - configure
    - configure-oh-my-zsh

# Finally, add exports etc to .zshrc /last/ (i.e. so they get added to whaterver
# .zshrc exists.
- include: zsh-zshrc.yml
  tags:
    - zsh
    - configure
    - configure-zsh
