---
- name: Find all current users.
  command: "users"
  register: users

- include: zsh.yml
  tags:
    - zsh
    - configure

- include: oh-my-zsh-install.yml
  tags:
    - oh-my-zsh
    - install
    - install-oh-my-zsh

- include: oh-my-zsh-zshrc.yml
  tags:
    - oh-my-zsh
    - configure
    - configure-oh-my-zsh
