---
- name: Check for existence of zsh
  command: "which xsh"
  register: zsh_exists
  failed_when: false

# Make sure /bin/zsh is contained in /etc/shells

# Set zsh to default shell if appropriate

# Install oh-my-zsh


- name: Debug `zsh_exists` variable
  debug:
    var: zsh_exists
