---
- name: "Install git"
  package:
    name: git
    state: present

- name: "OMZ | clone Oh My ZSH repo for user."
  git:
    repo: "{{ omz_git_repository }}"
    dest: "/root/.oh-my-zsh"
    update: true
    accept_hostkey: true
    version: "master"
  register: "omz_clone"

- name: "OMZ | set ownership on newly cloned repository."
  file:
    path: "/root/.oh-my-zsh"
    owner: "root"
    group: "root"
    recurse: true
  when: "omz_clone is changed"
