---
- name: Copy .zshrc into place if required.
  template:
    src: "{{ oh_my_zsh_zshrc_template }}"
    dest: "{{ zsh_users_home_path_prefix }}/.zshrc"
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
    backup: "yes"
  with_items: "{{ zsh_users }}"
  when: "{{ oh_my_zsh_zshrc_create }}"
  become: true
