---
- name: Copy .zshrc into place if required.
  template:
    src: "{{ oh_my_zsh_zshrc_template }}"
    dest: "{{ zsh_users_home_path_prefix }}/{{ item.user }}/.zshrc"
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
    backup: "yes"
  with_items: "{{ zsh_users }}"
  when: "{{ oh_my_zsh_zshrc_create }} and {{ zsh_users | length > 0 }}"
  become: true

- name: Export vars to .zshrc.
  lineinefile:
    dest: "{{ zsh_users_home_path_prefix }}/{{ item[0].user }}/.zshrc"
    line: "echo 'export {{ item[1] }}' >> {{ zsh_users_home_path_prefix }}/{{ item[0].user }}/.zshrc"
  with_nested:
    - "{{ zsh_users }}"
    - "{{ zsh_exports }}"
  when: "{{ zsh_users | length > 0 }} and {{ zsh_exports | > 0 }}"
