---
- name: Copy .zshrc into place if required.
  template:
    src: "{{ oh_my_zsh_zshrc_template }}"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
    backup: "yes"
  with_items: "{{ zsh_users }}"
  when: "'{{ item.user }}' in '{{ users.stdout }}' and {{ oh_my_zsh_zshrc_create }}"
  become: true
