---
- name: "OMZ | derive user .zshrc path."
  set_fact:
    omz_user_zshrc_path: "/root/.zshrc"

- name: "OMZ | template .zshrc into place if required."
  template:
    src: "zshrc.zsh-template.j2"
    dest: "{{ omz_user_zshrc_path }}"
    owner: "root"
    group: "root"
    backup: "{{ omz_zshrc_backup }}"
    force: "{{ omz_zshrc_force }}"
