---
# Note that we assume this file exists! lineinfile will fail if the file is
# not present.
- name: Export vars to .zshrc.
  lineinfile:
    dest: "{{ zsh_users_home_path_prefix }}/{{ item.user }}/.zshrc"
    line: |
  with_subelements:
    - "{{ zsh_users }}"
    - settings
  when: "{{ zsh_users | length > 0 }}"
