---
# Note that we assume this file exists! lineinfile will fail if the file is
# not present.
- name: Export vars to .zshrc.
  blockinfile:
    dest: "{{ zsh_users_home_path_prefix }}/{{ item.user }}/.zshrc"
    block: |
      "{{ item.settings }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK ({{ item.user }} SETTINGS)"
  with_items:
    - "{{ zsh_users }}"
  when: "{{ zsh_users | length > 0 }} and {{ item.settings | length > 0 }}"
