---
- name: Check for existence of ZSH.
  command: "which zsh"
  register: zsh_exists
  failed_when: "'{{ zsh_path }}' not in zsh_exists.stdout"
  always_run: true

- name: Ensure /etc/shells contains ZSH.
  lineinfile:
    dest: "/etc/shells"
    line: "{{ zsh_path }}"
  become: true

- name: Set ZSH shell as default for specified users.
  user:
    name: "{{ item.user }}"
    shell: "{{ zsh_path }}"
  with_items: "{{ zsh_users }}"
  when: "{{ zsh_users | length > 0 }}"
  become: true
