---
- name: Check for existence of ZSH.
  command: "which zsh"
  register: zsh_exists
  failed_when: "'{{ zsh_path }}' not in zsh_exists.stdout"
  always_run: true

- name: Ensure /etc/shells contians ZSH.
  lineinfile:
    dest: "/etc/shells"
    line: "{{ zsh_path }}"
  become: true

- name: Set ZSH shell as default for specified users.
  command: "sudo chsh -s {{ zsh_path }} {{ item.user }}"
  with_items: "{{ zsh_users }}"
  when: "'{{ item.user }}' in '{{ users.stdout }}'"
  become: true

debug: var=zsh_users

debug: var=users
