---
- name: "OMZ | establish home directory."
  set_fact:
    omz_user_home_dir: "/root"

- name: "OMZ | install zsh for Linux."
  package:
    name: "zsh"
    state: "present"
  when:
    - "ansible_system == 'Linux'"
    - "omz_install_zsh"


- name: "OMZ | get zsh installed path."
  shell: "command -v zsh"
  register: omz_zsh_installed_path
  changed_when: "false"

- name: "OMZ | set user shell to zsh."
  user:
    name: "root"
    shell: "{{ omz_zsh_installed_path.stdout }}"
